### ISSUE TITLE
Enabling Secure Cookie Flag Option

### ISSUE THREAD

**Issue by paulasharp** [atricore/atricore-idbus#1]
We are deploying an application and we are receiving the below from the security vendor as an issue. This may be related to the JOSSO 2.4 configuration. The application is running on Tomcat behind IIS 8.5. Does anyone have any ideas on how to configure JOSSO 2.4 or IIS to achieve the result in the remediation recommendations below?

Vulnerablility Details
If the secure flag is set on a cookie, then browsers will not submit the cookie in any requests that use an unencrypted HTTP connection, thereby preventing the cookie from being trivially intercepted by an attacker monitoring network traffic.

If the secure flag is not set, then the cookie will be transmitted in clear-text if the user visits any HTTP URLs within the cookie's scope. An attacker may be able to induce this event by feeding a user suitable links, either directly or via another web site. Even if the domain which issued the cookie does not host any content that is accessed over HTTP, an attacker may be able to use links of the form http://example.com:443/ to perform the same attack.

The following cookies were identified as being set by the application missing the ‘Secure’ attribute:

**Set-Cookie: JSESSIONID=x59sa1abcn.idbus-web-001;Path=/saml/josso/IDBUS
Set-Cookie: APP_TC_STATE=idBA53D4CAE41DA635;Path=/
Set-Cookie: APP_SP-APP-29147382_STATE=id23F7AB63ECA625EC;Path=/**

_NOTE: Above values are not actual._

Secure flag on cookies is often either misconfigured or overlooked during application development and subsequently transferred to the production environment.

Steps to reproduce:
For example, this issue can be reproduced by authenticating to the system (yoururl.com/saml/app), navigating to https://yoururl.com/saml/app/ index?classgrp=ABC_Def%3A%3AGHJ_Dog, submitting the HTTP GET request and intercepting the HTTP responses headers using intercepting proxy.

Remediation Recommendations
The secure flag should be set on all cookies that are used for transmitting sensitive data when accessing content over HTTPS. Session tokens in use should never be transmitted over unencrypted communications.

**Comment by gbrigandi** [comment]
For more detail please refer to : https://sourceforge.net/p/josso/discussion/399714/thread/cf6f6777/?limit=25#bdf2

**Comment by sgonzalezoyuela** [comment]
When you deploy JOSSO behind a reverse proxy, you may not secure the connection between the proxy and the SSO, therefore JOSSO assumes that cookies will be accessed in a non SSL connection.  There is no way to know that browser and proxy have secured the message exchange.

To solve this problem, JOSSO Provides a setting that allows you to force the "Secure" flag on cookies.  You have to go to **System Settings, Web** and check the **"Force Secure Cookies"** option. You can also manually edit the file **$JOSSO2_HOME/etc/org.ops4j.pax.web.cfg** and set the property 
**org.ops4j.pax.web.secureCookies** to **true**. (Remember to restart JOSSO after the change).

All JOSSO Relevant cookies will be marked as "Secure" , you will still see JSESSIONID cookies as unsecure, but the value is totally irrelevant to the SSO state, JOSSO has its own state management infrastructure that does not rely on the HTTP server session.  You should check that all cookies ending with "_STATE" are secured.

Sample Cookies without the force secure option enabled:
Set-Cookie: JSESSIONID=id....;Path=/IDBUS
Set-Cookie: IDA-OIDC_RP-1-OP_STATE=id...;Path=/

Sample Cookies with the force secure option enabled:
Set-Cookie: JSESSIONID=id....;Path=/IDBUS
Set-Cookie: IDA-OIDC_RP-1-OP_STATE=id...**;Secure**;Path=/

**Comment by paulasharp** [comment]
Thank you.  We will look at this.  Very much appreciated.




<http://www.jcatalog.de/>


jCatalog Software, Inc.
461 Jefferson Drive
Pittsburgh, PA 15228
USA

Office: +1 412 265 1999
Mobile: +1 412 721 8780
paul.sharp@jcatalog.com
www.jcatalog.com
